version: '3'

tasks:
  default:
    desc: "Build and run it"
    cmds:
      - task: build
      - task: run

  build:
    desc: "Assembles and links the executable"
    cmds:
      - clang -c src/c/debugging.c -o ./build/debugging_c.obj
      - nasm -f win64 src/asm/parse_file.asm -o ./build/parse_file.obj
      - nasm -f win64 src/asm/game.asm -o ./build/game.obj
      - lld-link ./build/game.obj ./build/parse_file.obj ./build/debugging_c.obj -entry:main -subsystem:console /defaultlib:kernel32.lib /defaultlib:msvcrt.lib /defaultlib:vcruntime.lib /defaultlib:ucrt.lib -out:./build/game.exe
  debug:
    desc: "Assembles and links the executable"
    cmds:
      - clang -c src/c/debugging.c -o ./build/debugging_c.obj
      - nasm -f win64 -g src/asm/parse_file.asm -o ./build/parse_file.obj
      - nasm -f win64 -g src/asm/game.asm -o ./build/adventure.obj
      - lld-link ./build/adventure.obj ./build/parse_file.obj ./build/debugging_c.obj -entry:main -subsystem:console /defaultlib:kernel32.lib /defaultlib:msvcrt.lib /defaultlib:vcruntime.lib /defaultlib:ucrt.lib -out:./build/adventure.exe /debug /pdb:./build/adventure.pdb
      - x64dbg "C:\Development\Private\assembler\build\adventure.exe"

  run:
    desc: "Start the built executable"
    cmd: ./build/game.exe

  clean:
    desc: "Clean up the compiled binary"
    cmds:
      - cmd /c "del /f /q .\build\*"