version: '3'

tasks:
  default:
    desc: "Build and run it"
    cmds:
      - task: build
      - task: run

  build:
    desc: "Assembles and links the executable"
    cmds:
      - nasm -f win64 game.asm -o ./build/game.obj 
      - lld-link ./build/game.obj -entry:main -subsystem:console -defaultlib:kernel32.lib -out:./build/game.exe

  file:
    desc: "Assembles and links the executable"
    cmds:
      - clang -c include/debug_log.c -o ./build/file/debug_log.obj
      - nasm -f win64 include/game_file_parser.asm -o ./build/file/game_file_parser.obj
      - nasm -f win64 file.asm -o ./build/file/file.obj
      - lld-link ./build/file/file.obj ./build/file/test_c.obj ./build/file/game_file_parser.obj ./build/file/debug_log.obj -entry:main -subsystem:console -defaultlib:kernel32.lib -out:./build/file.exe
      - ./build/file.exe

  debugfile:
    desc: "Assembles and links the executable"
    cmds:
      - nasm -f win64 -g include/game_file_parser.asm -o ./build/file/game_file_parser.obj
      - nasm -f win64 -g file.asm -o ./build/file/file.obj
      - lld-link ./build/file/file.obj ./build/file/test_c.obj ./build/file/game_file_parser.obj -entry:main -subsystem:console -defaultlib:kernel32.lib -out:./build/file_debug.exe /debug /pdb:./build/file_debug.pdb

  debug:
    cmds: 
      - nasm -f win64 -g game.asm -o ./build/game_debug.obj
      - lld-link ./build/game_debug.obj -entry:main -subsystem:console -defaultlib:kernel32.lib -out:./build/game_debug.exe /debug /pdb:./build/game_debug.pdb

  run:
    desc: "Start the built executable"
    cmd: ./build/game.exe

  clean:
    desc: "Clean up the compiled binary"
    cmds:
      - cmd /c "del /f /q .\build\*"