# build.yml
name: Build and Release x64 Assembly

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feature/file

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1

      - name: Install LLVM
        run: choco install llvm

      - name: Install make
        run: choco install make

      - name: Install rcedit
        run: |
          $rceditUrl = "https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe"
          Invoke-WebRequest -Uri $rceditUrl -OutFile "C:\rcedit.exe"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build with Makefile
        run: |
          mkdir -Force -Path build\obj\release\asm, build\bin\release
          make CONFIG=release FILE_NAME=game.bin SKIP_ANIMATIONS=0
          cd build\obj\release\asm
          echo "Current directory: $PWD"
          dir
        
      - name: Add version information
        run: |
          C:\rcedit.exe game.exe --set-version-string "CompanyName" "Benjamin Berger" 
          C:\rcedit.exe game.exe --set-version-string "FileDescription" "Game Executable"
          C:\rcedit.exe game.exe --set-version-string "ProductName" "x64 Assembly Text Adventure"
          C:\rcedit.exe game.exe --set-version-string "LegalCopyright" "Copyright © 2025 [Asorano]"

      # Rest of the workflow remains the same