name: Build and Release x64 Assembly

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1

      - name: Install LLVM
        run: choco install llvm

      - name: Install rcedit
        run: |
          $rceditUrl = "https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe"
          Invoke-WebRequest -Uri $rceditUrl -OutFile "C:\rcedit.exe"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Assemble Code
        run: |
          nasm -f win64 game.asm -o game.obj
          $WindowsKits = "C:\Program Files (x86)\Windows Kits\10"
          $LatestSDK = (Get-ChildItem "$WindowsKits\Lib" | Sort-Object -Property Name -Descending)[0].Name
          $LibPath = "$WindowsKits\Lib\$LatestSDK\um\x64"
          lld-link game.obj -entry:main -subsystem:console -libpath:"$LibPath" -defaultlib:kernel32.lib -out:game.exe

      - name: Add version information
        run: |
          C:\rcedit.exe game.exe --set-version-string "CompanyName" "Benjamin Berger" 
          C:\rcedit.exe game.exe --set-version-string "FileDescription" "Game Executable"
          C:\rcedit.exe game.exe --set-version-string "ProductName" "x64 Assembly Text Adventure"
          C:\rcedit.exe game.exe --set-version-string "LegalCopyright" "Copyright © 2025 [Asorano]"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game
          path: game.exe

      - name: Set up Git user
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
  
      - name: Create/Update latest tag
        run: |
            git tag -f latest
            git push origin latest --force

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: game
          path: ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: game.exe
          tag_name: latest
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
