name: Build and Release x64 Assembly

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for release'
        required: true
  push:
    tags:
      - 'v*'  # This triggers only when a tag like 'v1.0.0' is pushed

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1

      - name: Set up MINGW
        run: |
          choco install mingw -y

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Assemble Code
        run: |
          nasm -f win64 game.asm -o game.obj
          gcc -nostartfiles -o game.exe game.obj

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game
          path: game.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant the required permissions

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: game
          path: ./

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: game.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
