# build.yml
name: Build and Release x64 Assembly

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release Tag'
        required: true
        default: 'latest'
        type: string
      config:
        description: 'Build mode'
        required: true
        default: 'release'
        type: choice
        options:
          - 'release'
          - 'dev'
      skip_animations:
        description: 'Skip animations'
        required: true
        default: false
        type: boolean
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up NASM
        uses: ilammy/setup-nasm@v1

      - name: Install LLVM
        run: choco install llvm -y

      - name: Install make
        run: choco install make

      # THe makefile commands for creating the directories are ignored by the Github Action
      - name: Build with Makefile
        run: |
          mkdir -Force -Path build\obj\${{ github.event.inputs.config || 'release' }}\asm, build\obj\${{ github.event.inputs.config || 'release' }}\c, build\bin\${{ github.event.inputs.config || 'release' }}
          make build APP_ENTRY=main CONFIG=${{ github.event.inputs.config || 'release' }} SKIP_ANIMATIONS=${{ github.event.inputs.skip_animations == 'true' && '1' || '0' }}
          copy build\bin\${{ github.event.inputs.config || 'release' }}\game.exe game.exe
        
      # Setting file information

      - name: Install rcedit
        run: |
          $rceditUrl = "https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe"
          Invoke-WebRequest -Uri $rceditUrl -OutFile "C:\rcedit.exe"

      - name: Add version information
        run: |
          C:\rcedit.exe game.exe --set-version-string "CompanyName" "Benjamin Berger" 
          C:\rcedit.exe game.exe --set-version-string "FileDescription" "Game Executable"
          C:\rcedit.exe game.exe --set-version-string "ProductName" "x64 Assembly Text Adventure"
          C:\rcedit.exe game.exe --set-version-string "LegalCopyright" "Copyright © 2025 [Asorano]"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game
          path: |
            game.exe
            ${{ github.event.inputs.story_file || 'stories/game.bin' }}
  
      - name: Set up Git user
        run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
  
      - name: Create/Update latest tag
        run: |
            git tag -f latest
            git push origin latest --force
    
  # Create the new release
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: game
          path: ./

      - name: Create ZIP Archive
        run: zip -r game.zip game.exe ${{ github.event.inputs.story_file || 'stories/game.bin' }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            game.zip
          tag_name: ${{ github.event.inputs.release || 'latest' }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
